# Add 'converters' to any changes within converter scripts
converters:
  - converters/*

# Add 'ics' to any data upgrades or changes within ICS files
ics:
  - ics/*

# Add 'csv' to any data upgrades or changes within CSV files
csv:
  - csv/*

# Add 'xml' to any data upgrades or changes within XML files
xml:
  - xml/*

# Add 'json' to any data upgrades or changes within JSON files
json:
  - json/*

# Add 'srcdata' to all changes in csv, ics, xml, and json directories
srcdata:
  - ics/*
  - csv/*
  - xml/*
  - json/*
  - Tentative-Holiday-Data/*

# Add 'api' to any changes within api
api:
  - main.py
  - app.py

# Add 'docs' to new documentation & related files
docs:
  - docs/*
  - README.md
  - LICENSE
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md

# Add 'frontend' to any changes within frontend files
frontend:
  - public/*
